Todo/urls.py
from django.urls import path
from . import views

app_name = "Todo"
urlpatterns =[
    path("", views.index, name="index"),
    path("addtask", views.add_task, name="addtask"),
    path("deletetask", views.delete_task, name="deletetask"),
    path("search", views.search_task, name="searchtask")
]

todo_list/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('Todo/', include("Todo.urls") )
]

Todo/models.py
from django.db import models

# Create your models here.

Todo/views.py
from django.shortcuts import render
from django.http import HttpResponse,JsonResponse
from django import forms
import json, re

class new_task_form(forms.Form):
    task = forms.CharField(label="Add Task")

# Create your views here.

def index(request):
    if "tasks" not in request.session:
        request.session["tasks"] = []
    return render(request, "Todo/tasks.html",{
        "tasks": request.session["tasks"],
        "form": new_task_form()
    })

def add_task(request):
    if request.method == "POST":
        form = new_task_form(json.loads(request.body))
        if form.is_valid():
            task = form.cleaned_data["task"]
            request.session["tasks"] += [task]
            print("Task Added")
            data ={'added': True}
        else:
            print("Some error occured")
            data ={'added': False}
        return JsonResponse(data,status=200)
    else:
        return HttpResponse(status=200)

def delete_task(request):
    if request.method == "POST":
        request_data = json.loads(request.body)
        index_li = request_data.get('index')
        del request.session["tasks"][index_li]
        request.session.modified = True
        return HttpResponse(status=200)
    else:
        return HttpResponse(status=500)

def search_task(request):
    if request.method == 'POST':
        index_arr = []
        search_value = json.loads(request.body).get('search_value')
        reg = re.compile(f"^{search_value}")
        for i in range(len(request.session["tasks"])):
            if re.match(reg,request.session["tasks"][i]):
                index_arr.append(i)
        data = {
            'index_arr' : index_arr
        }
        return JsonResponse(data,status=200)
    else:
        return HttpResponse(status=500)


        

Todo/templates/Todo/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tasks</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'Todo/styles.css' %}">
</head>
<body>
    {% block body %}
    {% endblock %}
</body>
<script src="{% static 'Todo/index.js' %}"></script>
</html>

Todo/templates/Todo/tasks.html
{% extends "Todo/layout.html" %}

{% block body %}

<div id="search" data-search_url = "{% url 'Todo:searchtask' %}">
    <nav id="searchbar"class="navbar navbar-light bg-light">
        <div class="container-fluid">
          <form class="d-flex">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          </form>
        </div>
      </nav>
</div>

<div id="tasks" >
    <ul data-delete_url = "{% url 'Todo:deletetask' %}">
        {% for task in tasks %}
        <li class="taskli">{{ task }}
            <i class="fa fa-trash" aria-hidden="true"></i>
        </li>
        {% endfor %}
    </ul>
</div>

<div id="ad">
    <form class="addform"  data-task_url = "{% url 'Todo:addtask' %}">
        {% csrf_token %}
        <div class="addinput">
            {{form}}
        </div>
        <input type="submit" value="Add!">
    </form>
</div>

{% endblock %}